
repo_keyalias: runnervmtr4k5.zrqr2oex231ezjigm0txkepa0a.cx.internal.cloudapp.net


keydname: CN=runnervmtr4k5.zrqr2oex231ezjigm0txkepa0a.cx.internal.cloudapp.net, OU=F-Droid


keystorepass: YleFeNJ6lPO6xJ9egr6KnTRMAphM/c6v8ztIEKruavs=


keypass: YleFeNJ6lPO6xJ9egr6KnTRMAphM/c6v8ztIEKruavs=

