repo_url: "https://docedleiteproject.github.io/repo"
repo_name: "Doce de Leite"

repo_keyalias: runnervmtr4k5.ul30hyp0irqepaj0su5chck4eg.yx.internal.cloudapp.net


keydname: CN=runnervmtr4k5.ul30hyp0irqepaj0su5chck4eg.yx.internal.cloudapp.net, OU=F-Droid


keystorepass: XRAv1lLeP8CdVAfkKKKGSubrAmfdUSYhTd3OVZMi9C4=


keypass: XRAv1lLeP8CdVAfkKKKGSubrAmfdUSYhTd3OVZMi9C4=

