repo_url: "https://docedleiteproject.github.io/repo"
repo_name: "Doce de Leite"

repo_keyalias: runnervmtr4k5.sk4ncxdfcthutb4cvhnb1pmwjc.yx.internal.cloudapp.net


keydname: CN=runnervmtr4k5.sk4ncxdfcthutb4cvhnb1pmwjc.yx.internal.cloudapp.net, OU=F-Droid


keystorepass: SYfq28+kI9h+bfGldwg4oNqQHuljBIlOhle44Iz8Wxs=


keypass: SYfq28+kI9h+bfGldwg4oNqQHuljBIlOhle44Iz8Wxs=

