name: Publicar Repositório F-Droid

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-fdroid-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      # Instala o fdroidserver e atualiza o índice da pasta fdroid
      - name: Gerar índice do F-Droid
        run: |
          sudo apt-get update
          sudo apt-get install -y fdroidserver
          cd fdroid
          fdroid update --create-metadata

      # Publica o resultado na branch gh-pages
      - name: Deploy no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./fdroid
          
