name: Publicar Repositório F-Droid

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-fdroid-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      # Gera os metadados e os índices do repositório a partir do seu docedleite.apk
      - name: Gerar índice do F-Droid
        uses: fdroid/action-fdroid-repo@v1
        with:
          directory: fdroid

      # Publica o resultado na branch gh-pages
      - name: Deploy no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./fdroid
          
