name: Publicar Repositório F-Droid

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-fdroid-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Configurar e Gerar índice do F-Droid
        run: |
          sudo apt-get update
          sudo apt-get install -y fdroidserver
          
          # Cria o config.yml definindo a URL exata do repositório
          echo 'repo_url: "https://docedleiteproject.github.io/repo"' > config.yml
          echo 'repo_name: "Doce de Leite"' >> config.yml
          
          # Gera a chave e os índices
          fdroid update --create-key --create-metadata

      - name: Deploy no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          
